package exec;

import db.DbMetodoak;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Hiztegia;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ruben
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VentanaPrincipal() {

        initComponents();
        idiomaDetectado.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PalabraEntrada = new javax.swing.JTextField();
        jButtonTraducir = new javax.swing.JButton();
        jButtonIdiomaSalida = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonIdiomaEntrada = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PalabraSalida = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButtonEditarMenu = new javax.swing.JButton();
        idiomaDetectado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);
        setForeground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(700, 530));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DICCIONARIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 0, 140, 32);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(23, 47, 0, 0);

        PalabraEntrada.setMaximumSize(new java.awt.Dimension(60, 20));
        PalabraEntrada.setMinimumSize(new java.awt.Dimension(60, 20));
        PalabraEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalabraEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(PalabraEntrada);
        PalabraEntrada.setBounds(100, 90, 270, 40);

        jButtonTraducir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonTraducir.setText("TRADUCIR");
        jButtonTraducir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonTraducir.setMaximumSize(new java.awt.Dimension(60, 20));
        jButtonTraducir.setMinimumSize(new java.awt.Dimension(60, 20));
        jButtonTraducir.setName(""); // NOI18N
        jButtonTraducir.setPreferredSize(new java.awt.Dimension(20, 25));
        jButtonTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTraducirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTraducir);
        jButtonTraducir.setBounds(520, 90, 90, 40);

        jButtonIdiomaSalida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonIdiomaSalida.setText("Euskera");
        jButtonIdiomaSalida.setActionCommand("");
        jButtonIdiomaSalida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonIdiomaSalida.setMargin(new java.awt.Insets(5, 14, 2, 14));
        jButtonIdiomaSalida.setMaximumSize(new java.awt.Dimension(60, 20));
        jButtonIdiomaSalida.setMinimumSize(new java.awt.Dimension(60, 20));
        jButtonIdiomaSalida.setPreferredSize(new java.awt.Dimension(20, 25));
        jButtonIdiomaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIdiomaSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIdiomaSalida);
        jButtonIdiomaSalida.setBounds(380, 90, 130, 39);

        jLabel3.setText("Traducir a:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 70, 110, 14);

        jButtonIdiomaEntrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonIdiomaEntrada.setText("Castellano");
        jButtonIdiomaEntrada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonIdiomaEntrada.setMaximumSize(new java.awt.Dimension(60, 20));
        jButtonIdiomaEntrada.setMinimumSize(new java.awt.Dimension(60, 20));
        jButtonIdiomaEntrada.setName("JButtonIdiomaEntrada"); // NOI18N
        jButtonIdiomaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIdiomaEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIdiomaEntrada);
        jButtonIdiomaEntrada.setBounds(250, 50, 120, 35);

        PalabraSalida.setColumns(20);
        PalabraSalida.setRows(5);
        jScrollPane1.setViewportView(PalabraSalida);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(104, 165, 331, 130);

        jLabel4.setText("Resultado:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 150, 80, 10);

        jCheckBox1.setText("Detectar idioma");
        jCheckBox1.setToolTipText("");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(110, 60, 130, 23);

        jButtonEditarMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditarMenu.setText("Editar Diccionario");
        jButtonEditarMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEditarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarMenu);
        jButtonEditarMenu.setBounds(470, 180, 170, 100);

        idiomaDetectado.setText("Castellano (defecto)");
        getContentPane().add(idiomaDetectado);
        idiomaDetectado.setBounds(260, 60, 260, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIdiomaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIdiomaSalidaActionPerformed
        if (jButtonIdiomaSalida.getText().equalsIgnoreCase("Castellano")) {
            jButtonIdiomaSalida.setText("Euskera");
        } else if (jButtonIdiomaSalida.getText().equalsIgnoreCase("Euskera")) {
            jButtonIdiomaSalida.setText("English");
        } else {
            jButtonIdiomaSalida.setText("Castellano");
        }
    }//GEN-LAST:event_jButtonIdiomaSalidaActionPerformed

    private void jButtonIdiomaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIdiomaEntradaActionPerformed
        if (jButtonIdiomaEntrada.getText().equalsIgnoreCase("Castellano")) {
            jButtonIdiomaEntrada.setText("Euskera");
        } else if (jButtonIdiomaEntrada.getText().equalsIgnoreCase("Euskera")) {
            jButtonIdiomaEntrada.setText("English");
        } else {
            jButtonIdiomaEntrada.setText("Castellano");
        }
    }//GEN-LAST:event_jButtonIdiomaEntradaActionPerformed

    private void PalabraEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalabraEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PalabraEntradaActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            jButtonIdiomaEntrada.setVisible(false);
            idiomaDetectado.setVisible(true);

        } else {
            jButtonIdiomaEntrada.setVisible(true);
            idiomaDetectado.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButtonEditarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarMenuActionPerformed
        VentanaEditar editar = new VentanaEditar();
        editar.setVisible(true);


    }//GEN-LAST:event_jButtonEditarMenuActionPerformed

    private void jButtonTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTraducirActionPerformed
        

        if (jCheckBox1.isSelected()) {
            String PalabraTraducir = PalabraEntrada.getText();
            String idiomaEntrada = DbMetodoak.autoIdioma(PalabraTraducir);
            idiomaDetectado.setText(idiomaEntrada);
            PalabraSalida.setText(DbMetodoak.traducirPalabra(PalabraTraducir, idiomaEntrada, jButtonIdiomaSalida.getText()));

        }

        if (!jCheckBox1.isSelected()) {
            String PalabraTraducir = PalabraEntrada.getText();
            String idiomaEntrada = jButtonIdiomaEntrada.getText();

            PalabraSalida.setText(DbMetodoak.traducirPalabra(PalabraTraducir, idiomaEntrada, jButtonIdiomaSalida.getText()));

        }


    }//GEN-LAST:event_jButtonTraducirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaPrincipal ventana = new VentanaPrincipal();

                ventana.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PalabraEntrada;
    private javax.swing.JTextArea PalabraSalida;
    private javax.swing.JLabel idiomaDetectado;
    private javax.swing.JButton jButtonEditarMenu;
    private javax.swing.JButton jButtonIdiomaEntrada;
    private javax.swing.JButton jButtonIdiomaSalida;
    private javax.swing.JButton jButtonTraducir;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
